language: node_js
node_js:
- 0.10
addons:
  code_climate:
    repo_token:
      secure: gnpmh05SCdybzUpPPUmw+qEAaeldD/mhdV/1QuGVwPy/hs8SsiTzhspwJdPKtzoT12M6qXR9P8xh3yyiVegH/qsIONuAc7hSXJYd+PgFEYG4TcT9CxFoFVPKDkD6blYtzj8ty1ME6LFswqEghyTP6+xucqAu+isSkpbay5Jlemc=
after_script:
- cat coverage.lcov | codeclimate
