language: node_js
node_js:
- 0.12
addons:
  code_climate:
    repo_token:
      secure: mJWeypXw2zKQeyMRSDQVeWTem7R/rBgJuQuVTYRCZm1sPHbsfB4tNQ9uUwLEdBVfzEvNTFy4tp4leH66MSgSviU64o2kHS+inJxidYWvKdDoryTY+cUmAHByOJt2xMVc4VTgWR3XmYAbl6/tMdrwD68JHpFvgg4QnmWSqXg9w3g=
after_script:
- cat coverage.lcov | codeclimate
