language: node_js
node_js:
- 0.12
addons:
  code_climate:
    repo_token:
      secure: FxGSzWhfOOaaspvDjtv8x9CMgcjY0qkKuskFE9/pIKGN4g1ZeicMyTNYZacVb4lR6EUEDIY/ZDiOsDQtC28gzII50ndIRY1yzKhYv3pAroNUP81PNPA85j+F5pW9lZtD+tdzPP6X9IhyH4E7v5xYvknN6MnhLUM/ySp/wqZtuEU=
after_script:
- cat coverage.lcov | codeclimate
