language: node_js
node_js:
- 0.12
addons:
  code_climate:
    repo_token:
      secure: ohb+aIiBRqpcVMHKuziWZJP8PUJqnkw3p+CwDn2VaBSesd5MmF2R8QEf5rhkVyeMYWtP+r1NLGeNztekFUKXgERwIFn35OMJ4XzvJZShXjNi3/Hqrj1vOj6w48eQXAI3Ya256+oVFY1PDKzhQiw0jpjXzV1NfeYAa3ip1zWYhzs=
after_script:
- cat coverage.lcov | codeclimate
